;MyAnimeList-JSON 0.0.0.2 by ShaggyZE
#AutoIt3Wrapper_icon=mal.ico
#pragma compile(inputboxres, true)
#region Includes
#include-once
#include <Inet.au3>
#include <Json.au3>
#include <String.au3>
#include <MsgBoxConstants.au3>
#include <GuiButton.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <GuiComboBoxEx.au3>
#include <WindowsConstants.au3>
#include <GDIPlus.au3>
#include <IE.au3>
#include <Math.au3>
#include <ImageSearch2015.au3>
#include <GUIListView.au3>
#include <WinAPI.au3>
#include <File.au3>
#include <Misc.au3>
#include <vkConstants.au3>
#include <GUIScrollBars_Ex.au3>
#include <GuiScrollBars.au3>
#include <GuiScroll.au3>
#include <GUICtrl_SetResizing.au3>
#include <StaticConstants.au3>
#include <ProgressConstants.au3>
#include <ColorConstants.au3>
#include <GUIMenu.au3>
#endregion Includes
Global $szText, $szText, $szURL, $szAnime, $sValue1, $sValue2, $szDelay, $Username, $CSS, $CSSSynopsis, $CSSCover, $anime_id, $anime_ids
Local $hGUI = GUICreate("MyAnimeList-JSON                                                                         To Pause or Close Click the Autoit Icon in your System Tray at the Bottom Right", 900, 430, -1, -1, -1)
Local $hSysMenu = _GUICtrlMenu_GetSystemMenu($hGUI)
_GUICtrlMenu_DeleteMenu($hSysMenu, $SC_CLOSE, False)
_GUICtrlMenu_DeleteMenu($hSysMenu, $SC_MAXIMIZE, False)
GUISetIcon(@ScriptDir & "\mal.ico")
;========================================================
;GUI Frontend$
$ButtonS = GUICtrlCreateButton("Start", 5, 5, 45, 25)
GUICtrlSetTip(-1, "Click to Start")
$UsernameINP = GUICtrlCreateInput("Username", 80, 5, 100)
GUICtrlSetTip(-1, "Your Mal Username")
GUICtrlCreateLabel("Output", 210, 10, 65, 25)
GUICtrlSetTip(-1, "This is where your CSS code will be")
$Progress = GUICtrlCreateLabel("", 60, 33, 100, 20, $SS_CENTER, $WS_EX_TOPMOST)
GUICtrlSetTip(-1, "")
GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
GUICtrlCreateLabel("Delay", 5, 60, 65, 25)
GUICtrlSetTip(-1, "Milliseconds between Scraping MyAnimeList.net")
GUISetState(@SW_SHOW)
;Global $sValue1 = InputBox("Input Starting Anime ID#", "Which anime #ID would you like to start with?", "41621", " M5")
;Global $sValue2 = InputBox("Input Finishing Anime ID#", "Which anime #ID would you like to finish with?", "45700", " M5")
;Global $szDelay = InputBox("Input Delay", "How long of a delay between anime scraping?(1000 equals 1 second)", "2000", " M5")
$szFile1 = "scrape.txt"
$szFile2 = "mal.css"
$szFile3 = "scrape.html"
$sValue1 = 0
$sValue2 = 50000
$szDelay = 2000
$CSS = '#tags-[ID]:after {font-family: Finger Paint; content: "[DESC]";}'
$x = @DesktopWidth - 150
$y = @DesktopHeight - 62.5
GUISetState(@SW_SHOW, $hGUI)
While GUIGetMsg() <> $GUI_EVENT_CLOSE
Sleep(10)
	$nMsg = GUIGetMsg()

	Switch $nMsg
		;Exit
		Case $GUI_EVENT_CLOSE
			Exit (20)
		;Start
		Case $ButtonS
			ToolTip("Scraping MAL data...", $x, $y)
			Sleep(2000); Sleep to give tooltip time to display
			FileDelete($szFile2)
			$szText = '/* Generated by MAL List Tool http://burntjello.webs.com' & @CRLF & 'Template=' & $CSS & @CRLF & 'MatchTemplate=#more[ID] ' & @CRLF & '*/'
			FileWrite($szFile2,$szText)
			;_ScrapeMALAnime()
			_ScrapeMALJSONAnime()
			FileDelete($szFile1)
			FileDelete($szFile3)
			Sleep(2000); Sleep to give tooltip time to display
		Case Else
			;MsgBox(0,"",$nMsg)
	EndSwitch
WEnd


Func _ParseTag($CSS, $szAnime)
$szText1 = FileRead($szFile1,FileGetSize($szFile1))
$szText1 = StringReplace($szText1, @LF, "")
$szText1 = StringReplace($szText1, @CR, "")
$szText1 = StringReplace($szText1, @CRLF, "")
$szText1 = StringReplace($szText1, '"', '')
$szText1 = StringReplace($szText1, "<br />", "")
$szText1 = StringReplace($szText1, "<i>", "")
$szText1 = StringReplace($szText1, "</i>", "")
$szText1 = StringReplace($szText1, "&quot;", '\"')
$szText1 = StringReplace($szText1, "&eacute;", "é")
$szText1 = StringReplace($szText1, "&euml;", "é")
$szText1 = StringReplace($szText1, "&auml;", "ä")
$szText1 = StringReplace($szText1, "Å", "o")
$szText1 = StringReplace($szText1, "&amp;", "&")
$szText1 = StringReplace($szText1, "&rsquo;", "'")
$szText1 = StringReplace($szText1, "&#039;", "'")
$szText1 = StringReplace($szText1, "&mdash;", "-")
$szText1 =  @CRLF & '#tags-' & $szAnime & ':after {font-family: Finger Paint; content: "' & $szText1 & '";}'
FileWrite($szFile2,$szText1)
EndFunc   ;==>_ParseTag

Func _ScrapeMALAnime()
For $szAnime = $sValue1 to $sValue2
	GUICtrlSetData($Progress, $sValue1 & " of " & $sValue2)
	$szURL = "https://myanimelist.net/anime/" & $szAnime
	ToolTip($szAnime & " Scanned.", $x, $y)
	Sleep($szDelay); Sleep to give tooltip time to display
    $source = _INetGetSource($szURL) ;get html
    FileDelete($szFile3)
	FileWrite(@ScriptDir & "\" & $szFile3, $source); save file
    Local $read = FileRead(@ScriptDir & "\" & $szFile3) ;read file
    Local $readtitle = _StringBetween($read, '<p itemprop="description">', '</p>') ;read URL and title from file
    If IsArray($readtitle) Then
		_FileWriteFromArray(@ScriptDir & '\' & $szFile1, $readtitle)
		_ParseTag($CSS, $szAnime)
    Else
		Local $readtitle = _StringBetween($read, 'Synopsis</h2></div>', '<') ;read URL and title from file
		If IsArray($readtitle) Then
			_FileWriteFromArray(@ScriptDir & '\' & $szFile1, $readtitle)
			_ParseTag($CSS, $szAnime)
		EndIf
    EndIf
Next
EndFunc   ;==>_Scrape

Func _ScrapeMALJSONAnime()
_GetMALAnimeJSON()
EndFunc   ;==>_ScrapeMALJSONAnime

Func _GetMALAnimeJSON()
Local $i = 0

While 1
	$Username = GUICtrlRead($UsernameINP)
	$URL = "https://myanimelist.net/animelist/" & $Username & "/load.json?status=7&offset=" & $i
	$data = _INetGetSource($URL)
	$object = Json_Decode($data)
	;msgbox("","",$data)
	If $object = "" Then ExitLoop
    If @error Then ExitLoop
        $anime_id = Json_Get($object, 'anime_id')
        ConsoleWrite('$anime_id = ' & $anime_id & @CRLF ) ;### Debug Console
		$anime_ids = $anime_ids & $anime_id
    $i += 300
WEnd
EndFunc   ;==>_GetMALAnimeJSON