;MyAnimeList-JSON 0.0.0.9 by ShaggyZE
#AutoIt3Wrapper_icon=mal.ico
#pragma compile(inputboxres, true)
#region Includes
#include-once
#include <Inet.au3>
#include <Json.au3>
#include <String.au3>
#include <MsgBoxConstants.au3>
#include <GuiButton.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <GuiComboBoxEx.au3>
#include <WindowsConstants.au3>
#include <GDIPlus.au3>
#include <IE.au3>
#include <Math.au3>
#include <ImageSearch2015.au3>
#include <GUIListView.au3>
#include <WinAPI.au3>
#include <File.au3>
#include <Misc.au3>
#include <vkConstants.au3>
#include <GUIScrollBars_Ex.au3>
#include <GuiScrollBars.au3>
#include <GuiScroll.au3>
#include <GUICtrl_SetResizing.au3>
#include <StaticConstants.au3>
#include <ProgressConstants.au3>
#include <ColorConstants.au3>
#include <GUIMenu.au3>
#endregion Includes
Global $szText, $szText, $szURL, $szAnime, $sValue1, $sValue2, $szDelay, $Username, $CSS, $Method, $anime_id, $anime_ids
Local $hGUI = GUICreate("MyAnimeList-JSON                                                                         To Pause or Close Click the Autoit Icon in your System Tray at the Bottom Right", 900, 430, -1, -1, -1)
Local $hSysMenu = _GUICtrlMenu_GetSystemMenu($hGUI)
_GUICtrlMenu_DeleteMenu($hSysMenu, $SC_CLOSE, False)
_GUICtrlMenu_DeleteMenu($hSysMenu, $SC_MAXIMIZE, False)
GUISetIcon(@ScriptDir & "\mal.ico")
;GUI Frontend
$ButtonS = GUICtrlCreateButton("Start", 5, 5, 45, 20)
GUICtrlSetTip(-1, "Click to Start")
$UsernameINP = GUICtrlCreateInput("ShaggyZE", 80, 5, 100, 20)
GUICtrlSetTip(-1, "Your Mal Username")
GUICtrlCreateLabel("Output", 225, 10, 65, 20)
GUICtrlSetTip(-1, "This is where your CSS code will be")
$Progress = GUICtrlCreateLabel("", 60, 33, 100, 20, $SS_CENTER, $WS_EX_TOPMOST)
GUICtrlSetTip(-1, "")
GUICtrlCreateLabel("Delay", 5, 60, 65, 20)
GUICtrlSetTip(-1, "Milliseconds between Scraping MyAnimeList.net")
$DelayINP = GUICtrlCreateInput("2000", 5, 80, 40, 20)
GUICtrlSetTip(-1, "Milliseconds between Scraping MyAnimeList.net")
GUICtrlCreateLabel("Template", 5, 110, 65, 20)
GUICtrlSetTip(-1, "CSS Template")
$TemplateINP = GUICtrlCreateInput("#tags-[ID]:after {font-family: Finger Paint; content: '[DESC]';}", 5, 130, 220, 20)
GUICtrlSetTip(-1, "CSS Template")
GUICtrlCreateLabel("Method", 5, 160, 65, 20)
GUICtrlSetTip(-1, "Method of scraping Data for CSS")
$methodCMB = GUICtrlCreateCombo("MyAnimeList-Anime", 5, 180, 150, 20)
GUICtrlSetData(-1, "MyAnimeList-Manga|MyAnimeList-Anime-JSON|MyAnimeList-Manga-JSON")
GUICtrlSetTip(-1, "Method of scraping Data for CSS")
GUISetState(@SW_SHOW)
$szFile1 = "scrape.txt"
$szFile2 = "mal.css"
$szFile3 = "scrape.html"
$sValue1 = 0
$sValue2 = 50000
$x = @DesktopWidth - 150
$y = @DesktopHeight - 62.5
GUISetState(@SW_SHOW, $hGUI)
While GUIGetMsg() <> $GUI_EVENT_CLOSE
Sleep(10)
	$nMsg = GUIGetMsg()

	Switch $nMsg
		;Exit
		Case $GUI_EVENT_CLOSE
			Exit (20)
		;Start
		Case $ButtonS
			$Method = GUICtrlRead($methodCMB)
			If $Method = "MyAnimeList-Anime" Then
				Global $sValue1 = InputBox("Input Starting Anime ID#", "Which anime #ID would you like to start with?", "0", " M5")
				Global $sValue2 = InputBox("Input Finishing Anime ID#", "Which anime #ID would you like to finish with?", "50000", " M5")
				If $sValue1 = "" Then $sValue1 = 0
				If $sValue2 = "" Then $sValue2 = 50000
				ToolTip("Scraping MAL data...", $x, $y)
				Sleep(2000)
				FileDelete($szFile2)
				$CSS = GUICtrlRead($TemplateINP)
				$szText = '/* Generated by MyAnimeList-JSON https://github.com/shaggyze/MyAnimeList-JSON' & @CRLF & 'Template=' & $CSS & '*/'
				FileWrite($szFile2,$szText)
				_ScrapeMALAnime()
				FileDelete($szFile1)
				FileDelete($szFile3)
				Sleep(2000)
			ElseIf $Method = "MyAnimeList-Anime-JSON" Then
			_ScrapeMALJSONAnime()
			EndIf
		Case Else
			;MsgBox(0,"",$nMsg)
	EndSwitch
WEnd


Func _ParseDESC($szAnime)
$parseStr =  FileRead($szFile1,FileGetSize($szFile1))
$parseStr =  StringReplace($parseStr, @LF, "")
$parseStr =  StringReplace($parseStr, @CR, "")
$parseStr =  StringReplace($parseStr, @CRLF, "")
$parseStr =  StringReplace($parseStr, '"', '')
$parseStr =  StringReplace($parseStr, "'", '')
$parseStr =  StringReplace($parseStr, "<br />", "")
$parseStr =  StringReplace($parseStr, "<i>", "")
$parseStr =  StringReplace($parseStr, "</i>", "")
$parseStr =  StringReplace($parseStr, "&quot;", '\"')
$parseStr =  StringReplace($parseStr, "&eacute;", "é")
$parseStr =  StringReplace($parseStr, "&euml;", "é")
$parseStr =  StringReplace($parseStr, "&auml;", "ä")
$parseStr =  StringReplace($parseStr, "Å", "o")
$parseStr =  StringReplace($parseStr, "&amp;", "&")
$parseStr =  StringReplace($parseStr, "&rsquo;", "")
$parseStr =  StringReplace($parseStr, "&#039;", "")
$parseStr =  StringReplace($parseStr, "&#x27;", "")
$parseStr =  StringReplace($parseStr, "&mdash;", "-")
$szText1 = @CRLF & $CSS
$szText1 = StringReplace($szText1, "[ID]", $szAnime)
$szText1 = StringReplace($szText1, "[DESC]", $parseStr)
FileWrite($szFile2, $szText1)
EndFunc   ;==>_ParseTag

Func _ScrapeMALAnime()
While $sValue1 <= $sValue2
	$szAnime = $sValue1
	GUICtrlSetData($Progress, $sValue1 & " of " & $sValue2)
	$szURL = "https://myanimelist.net/anime/" & $szAnime
	ToolTip($szAnime & " Scanned.", $x, $y)
	Sleep(GUICtrlRead($DelayINP))
    $source = _INetGetSource($szURL)
    FileDelete($szFile3)
	FileWrite(@ScriptDir & "\" & $szFile3, $source)
    Local $read = FileRead(@ScriptDir & "\" & $szFile3)
    Local $readtitle = _StringBetween($read, '<p itemprop="description">', '</p>')
    If IsArray($readtitle) Then
		_FileWriteFromArray(@ScriptDir & '\' & $szFile1, $readtitle)
		_ParseDESC($szAnime)
    Else
		Local $readtitle = _StringBetween($read, 'Synopsis</h2></div>', '<')
		If IsArray($readtitle) Then
			_FileWriteFromArray(@ScriptDir & '\' & $szFile1, $readtitle)
			_ParseDESC($szAnime)
		EndIf
    EndIf
	$sValue1 = $sValue1 + 1
WEnd
EndFunc   ;==>_Scrape

Func _ScrapeMALJSONAnime()
_GetMALAnimeJSON()
EndFunc   ;==>_ScrapeMALJSONAnime

Func _GetMALAnimeJSON()
Local $i = 0

While 1
	$Username = GUICtrlRead($UsernameINP)
	$URL = "https://myanimelist.net/animelist/" & $Username & "/load.json?status=7&offset=" & $i
	$data = _INetGetSource($URL)
	$object = Json_Decode($data)
	msgbox("","",$data)
	If $object = "" Then ExitLoop
    If @error Then ExitLoop
        $anime_id = Json_Get($object, 'anime_id')
        ConsoleWrite('$anime_id = ' & $anime_id & @CRLF ) ;### Debug Console
		$anime_ids = $anime_ids & $anime_id
    $i += 300
WEnd
EndFunc   ;==>_GetMALAnimeJSON